### ISSUE TITLE
Fix min height of agenda section

### ISSUE THREAD

**Issue by fbiville** [hack-commit-push/paris2021#9]
See https://paris2021.hack-commit-pu.sh/#agenda
and the actual problem: https://github.com/hack-commit-push/paris2021/blob/a52276dbaf59a53d4934bf1a2993e0be47a6666d/css/main.scss#L123-L127

**Comment by Siddharth1010** [comment]
Hi @fbiville , What is the problem here?

**Comment by fbiville** [comment]
@Siddharth1010 if you look at other `<section>`s (such as https://paris2021.hack-commit-pu.sh/#venue), you'll see they occupy the whole screen height). This is not the case for https://paris2021.hack-commit-pu.sh/#agenda and it should be.

**Comment by Siddharth1010** [comment]
@fbiville So I could either just remove `:not(#agenda)` or add `min-height: 100%; ` to `body>section:nth-child(odd)` right?
Which one would you like me to do?

**Comment by Siddharth1010** [comment]
Actually I think its better to remove `:not(#agenda)` as the other would involve re-aligning it to the center. I will change it and create  PR. Do let me know if it is okay :)
